name = "ReproducibleLiteratePage"
uuid = "963ca19c-1af9-4710-a933-a2a16c7180a2"
authors = ["Tamás K. Papp <tkpapp@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[compat]
julia = "1.6"
DocStringExtensions = "0.7, 0.8, 0.9"
Literate = "2"
Tar = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
